# Generated by Django 3.2.8 on 2021-10-24 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_no', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=32)),
                ('small_name', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('pay_interval', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
