# Generated by Django 3.2.8 on 2021-10-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('friendly_name', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='membership',
            name='description',
        ),
        migrations.AddField(
            model_name='membership',
            name='all_classes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.discipline'),
        ),
    ]
